import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { ToggleSidebar } from "@/components/sidebar/toggle-sidebar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider defaultOpen={false}>
          <AppSidebar />
          <SidebarInset className="p-4">
            <div className="flex justify-between items-center">
              <ToggleSidebar />

              <div className="flex items-center gap-x-2">
                <Button asChild>
                  <Link href="/auth">Log in</Link>
                </Button>

                <Button asChild variant="outline">
                  <Link href="/auth">Sign up</Link>
                </Button>
              </div>
            </div>

            {children}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
